---
-- Setup Snowflake environment
---

USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE SAMPLE_DATA;

CREATE OR REPLACE SCHEMA SAMPLE_SALES;

CREATE WAREHOUSE IDENTIFIER('"SAMPLE_SALES_WH"') 
COMMENT = '' 
WAREHOUSE_SIZE = 'X-Small' 
AUTO_RESUME = true 
AUTO_SUSPEND = 300 
ENABLE_QUERY_ACCELERATION = false 
WAREHOUSE_TYPE = 'STANDARD'
;

CREATE WAREHOUSE IDENTIFIER('"NOTEBOOK_WH"') 
COMMENT = '' 
WAREHOUSE_SIZE = 'Medium' 
AUTO_RESUME = true 
AUTO_SUSPEND = 300 
ENABLE_QUERY_ACCELERATION = false 
WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED' 
RESOURCE_CONSTRAINT = 'MEMORY_16X'

---
-- Generate Sample Queries with Snowflake Co Pilot
---

/* Generated by Snowflake Copilot */
/* Top 5 customers by total spending */
SELECT
  customers.customer_id,
  customers.first_name,
  customers.last_name,
  SUM(sales_fact.total_amount) AS total_spent
FROM
  sales_fact
  JOIN customers ON sales_fact.customer_id = customers.customer_id
GROUP BY
  customers.customer_id,
  customers.first_name,
  customers.last_name
ORDER BY
  total_spent DESC
LIMIT
  5;
  
/* Generated by Snowflake Copilot */
-- Comparison of total sales between different years
SELECT
  time_dimension.year,
  SUM(sales_fact.total_amount) AS total_sales
FROM
  sales_fact
  JOIN time_dimension ON sales_fact.date_id = time_dimension.date_id
GROUP BY
  time_dimension.year
ORDER BY
  time_dimension.year;
  
/* Generated by Snowflake Copilot */
-- Comparison of average sale amounts between different store types
SELECT
  stores.store_type,
  AVG(sales_fact.total_amount) AS average_sale
FROM
  sales_fact
  JOIN stores ON sales_fact.store_id = stores.store_id
GROUP BY
  stores.store_type;

 ---
 -- Generate descriptions with Snowflake Cortex
 ---

-- https://docs.snowflake.com/en/user-guide/ui-snowsight-cortex-descriptions

---
-- Cortex Analyst semantic model specification
---

-- https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-analyst/semantic-model-spec
-- https://github.com/Snowflake-Labs/semantic-model-generator
-- https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-analyst/verified-query-repository

CREATE OR REPLACE STAGE SAMPLE_SALES_STAGE
;

 ---
 -- Snowflake Cortex Analyst
 ---

 -- https://www.snowflake.com/en/engineering-blog/cortex-analyst-joins-star-snowflake-schemas/
