# .streamlit/secrets.toml

[snowflake]
user = "python"
password = "12BeSecure"
role = "datascience"
account = "ja75028.west-europe.azure"
warehouse = "analytics_wh"
database = "demo_db"
schema = "pets"

