-- Use SYSADMIN role
USE ROLE SYSADMIN
;

-- Create the Sandbox Database
CREATE OR REPLACE TRANSIENT DATABASE SANDBOX_DB
;

GRANT USAGE ON DATABASE SANDBOX_PLAYDB TO ROLE BI_TOOL
;

GRANT USAGE ON DATABASE SANDBOX_PLAYDB TO ROLE ELT_TOOL
;

-- Create Database Schema's

-- Use CDWA role
USE ROLE DBA
;

-- Create schema NUTTSPACE
CREATE OR REPLACE TRANSIENT SCHEMA NUTTSPACE
;


-- Define the grants as follows:
GRANT USAGE ON SCHEMA NUTTSPACE TO ROLE ELT_TOOL
;

GRANT USAGE ON SCHEMA NUTTSPACE TO ROLE BI_TOOL
;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA NUTTSPACE TO ROLE ELT_TOOL
;

GRANT SELECT ON FUTURE TABLES IN SCHEMA NUTTSPACE TO ROLE BI_TOOL
;

GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA NUTTSPACE TO ROLE ELT_TOOL
;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA NUTTSPACE TO ROLE BI_TOOL
;

GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA NUTTSPACE TO ROLE ELT_TOOL
;

GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA NUTTSPACE TO ROLE ELT_TOOL
;

