-- Use SECURITYADMIN role
USE ROLE SECURITYADMIN
;

-- Grant role SECURITYADMIN
GRANT ROLE SECURITYADMIN TO USER RMATCHED
;

-- Grant role DBA
GRANT ROLE DBA TO USER MARTINI
;

-- Grant role DEVELOPER
GRANT ROLE DEVELOPER TO USER HARDING
;

-- Grant role ANALYST
GRANT ROLE ANALYST TO USER TABER
;