/*
 Setup Resource monitors to make sure the burning of credits does not exceed your expectations
 */

-- Use ACCOUNTADMIN role
USE ROLE ACCOUNTADMIN
;

-- Create Resource Monitors (including notification) for various limits
CREATE RESOURCE MONITOR ACCOUNT_LIMIT_250
WITH CREDIT_QUOTA = 250
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 100 PERCENT DO NOTIFY
;

CREATE RESOURCE MONITOR ACCOUNT_LIMIT_300
WITH CREDIT_QUOTA = 300
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 100 PERCENT DO SUSPEND
;

CREATE RESOURCE MONITOR ACCOUNT_LIMIT_375
WITH CREDIT_QUOTA = 375
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 100 PERCENT DO SUSPEND_IMMEDIATE
;