-- Use SYSADMIN role
USE ROLE SYSADMIN
;

-- Create X-Small Warehouse
CREATE WAREHOUSE SANDBOX_XS WITH
WAREHOUSE_SIZE = XSMALL
MAX_CLUSTER_COUNT = 2
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 120
ALTER RESUME = TRUE
COMMENT = 'Use this as the default warehouse for the development initially.'
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_XS TO CDWA
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_XS TO  ELT_TOOL
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_XS TO  BI_TOOL
;

-- Create Small Warehouse
CREATE WAREHOUSE SANDBOX_SMALL WITH
WAREHOUSE_SIZE = SMALL
MAX_CLUSTER_COUNT = 2
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 120
ALTER RESUME = TRUE
COMMENT = 'Use this as the warehouse if you want to improve query performance.'
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_SMALL TO CDWA
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_SMALL TO  ELT_TOOL
;

GRANT USAGE, OPERATE ON WAREHOUSE SANDBOX_SMALL TO  BI_TOOL
;

--
--

-- Make sure Snowflake provided warehouses cannot be modified by accident.
REVOKE MODIFY ON WAREHOUSE DEMO_WH FROM ROLE PUBLIC;
REVOKE MODIFY ON WAREHOUSE LOAD_WH FROM ROLE PUBLIC;

--
--

-- Set default warehouses for the users

-- Use SECURITYADMIN role
USE ROLE SECURITYADMIN
;

ALTER USER RMURPHY SET DEFAULT_WAREHOUSE = PLAY_XS
;

ALTER USER MARTINI SET DEFAULT_WAREHOUSE = PLAY_XS
;

ALTER USER HARDING SET DEFAULT_WAREHOUSE = PLAY_XS
;

ALTER USER TABER SET DEFAULT_WAREHOUSE = PLAY_XS
;

